import fs from 'fs';
import path from 'path';

const html = fs.readFileSync(
  path.join(__dirname, '..', '..', 'public', 'asm_examples.html'),
  'utf-8'
);

describe('asm_examples.html', () => {
  describe('page structure', () => {
    it('has a top-level ASM Examples heading', () => {
      expect(html).toMatch(/<h1>ASM Examples<\/h1>/);
    });

    it('has an introduction section explaining the page', () => {
      expect(html).toMatch(/<section id="introduction">/);
      expect(html).toMatch(/worked examples — one per editor/);
    });

    it('links back to the Z80 Assembly Introduction', () => {
      expect(html).toContain('href="/z80_book.html"');
    });

    it('has a UDG example section with an anchor target matching the docs link', () => {
      expect(html).toMatch(/<section id="udg-example">/);
      expect(html).toMatch(/<h1>UDG: Displaying an Exported Sprite<\/h1>/);
    });
  });

  describe('UDG example sub-sections', () => {
    const expectedHeadingIds = [
      'udg-centring',
      'udg-addressing',
      'udg-draw-loop',
      'udg-border-flags',
      'udg-exported-data',
      'udg-source',
      'udg-running',
    ];

    it.each(expectedHeadingIds)('includes the %s sub-section', (id) => {
      expect(html).toContain(`id="${id}"`);
    });
  });

  describe('generic wording around exported filenames', () => {
    it('explains that the exported filename will be specific to the user\'s own export', () => {
      expect(html).toMatch(/whatever filename <em>you<\/em> choose/);
      expect(html).toMatch(/whatever filename your export was saved as/);
    });

    it('frames the bundled udg_7_x_3.asm file as just one example, not the only shape of file', () => {
      expect(html).toMatch(/the bundled 7x3-character sprite/);
      expect(html).toMatch(/This is the same shape of file the editor generates for <em>any<\/em> sprite you export/);
    });

    it('explains that dimensions and derived constants come from whatever file is exported', () => {
      expect(html).toMatch(/come from whichever file the <code>include<\/code> line pulls in/);
      expect(html).toMatch(/Export a sprite of your own with different dimensions and the assembled values.*will be different/);
    });

    it('does not present the 7x3 canvas size as a fixed requirement', () => {
      // Mentions of 7x3 / 21 chars should always be qualified as "the bundled" example,
      // not stated as something the user's own export must match.
      expect(html).not.toMatch(/must be 7x3/i);
      expect(html).not.toMatch(/your sprite (?:must|should) be (?:7|21)/i);
    });
  });

  describe('bundled exported data example (udg_7_x_3.asm)', () => {
    it('includes a heading naming the bundled exported data file', () => {
      expect(html).toMatch(/<h2 id="udg-exported-data">The Exported Data: udg_7_x_3\.asm<\/h2>/);
    });

    it('includes the generated header comment with sprite dimensions', () => {
      expect(html).toContain('; ZX Spectrum UDG Sprite Data');
      expect(html).toContain('; Generated by ZX Spectrum UDG Editor');
      expect(html).toContain('; Sprite dimensions: 7x3 characters (56x24 pixels)');
      expect(html).toContain('; Total characters: 21');
    });

    it('defines the constants the viewer relies on', () => {
      expect(html).toContain('SPRITE_WIDTH');
      expect(html).toContain('SPRITE_HEIGHT');
      expect(html).toContain('SPRITE_CHARS');
      expect(html).toContain('UDG_BYTES');
      expect(html).toContain('FIRST_UDG_CHAR');
    });

    it('includes the raw pixel and attribute data labels', () => {
      expect(html).toMatch(/<span class="label">sprite_udg_data<\/span>:/);
      expect(html).toMatch(/<span class="label">sprite_attr_data<\/span>:/);
    });
  });

  describe('viewer source example (udg_viewer.asm)', () => {
    it('includes a heading naming the viewer source file', () => {
      expect(html).toMatch(/<h2 id="udg-source">Source: udg_viewer\.asm<\/h2>/);
    });

    it('includes the complete viewer with org, include and end directives', () => {
      expect(html).toMatch(/org\s*<\/span>\s*<span class="number">\$8000<\/span>/);
      expect(html).toContain('include');
      expect(html).toContain('"udg_7_x_3.asm"');
      expect(html).toMatch(/<span class="directive">end<\/span>\s*start/);
    });

    it('includes the centring, addressing and draw-loop logic', () => {
      expect(html).toContain('START_COL');
      expect(html).toContain('START_ROW');
      expect(html).toContain('END_COL');
      expect(html).toContain('PIXEL_BASE');
      expect(html).toContain('ATTR_BASE');
      expect(html).toContain('draw_loop');
      expect(html).toContain('halt_loop');
    });

    it('includes the border flag colour-change instructions', () => {
      expect(html).toMatch(/<span class="keyword">out<\/span>\s*\(254\), a/);
      expect(html).toContain('Red border = code is running');
      expect(html).toContain('White border = display ready');
    });
  });

  describe('assembling and running instructions', () => {
    it('shows the pasmo and fuse commands referenced elsewhere on the page', () => {
      expect(html).toContain('pasmo --tapbas udg_viewer.asm udg_viewer.tap');
      expect(html).toContain('fuse --tape udg_viewer.tap --auto-load');
    });

    it('tells the reader to edit the include line to match their own export', () => {
      expect(html).toMatch(/edit the <code>include<\/code> line/);
      expect(html).toMatch(/to match whatever filename your export was saved as/);
    });
  });

  describe('sidebar navigation', () => {
    it('renders the collapsible examples menu controls', () => {
      expect(html).toContain('id="examples-toggle"');
      expect(html).toContain('id="examples-list"');
      expect(html).toContain('toggleExamplesMenu');
    });

    it('defines the toggleExamplesMenu script that flips aria-expanded and the arrow glyph', () => {
      expect(html).toMatch(/function toggleExamplesMenu\(\)/);
      expect(html).toContain("btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false')");
    });
  });
});
