import { Attribute, DrawBounds } from '@/types';
import { CHAR_SIZE, MAX_UDG_CHARS } from '@/constants';

interface ExportParams {
  pixels: boolean[][];
  attributes: Attribute[][];
  bounds: DrawBounds;
  fileName: string;
}

// Export as ASM file (compact, game-ready format)
export function exportASM({ pixels, attributes, bounds, fileName }: ExportParams): boolean {
  const { minCharX, minCharY, width: exportWidth, height: exportHeight } = bounds;
  const totalChars = exportWidth * exportHeight;

  if (totalChars > MAX_UDG_CHARS) {
    alert(`Drawn content spans ${totalChars} characters, but ZX Spectrum only has ${MAX_UDG_CHARS} UDG slots. Please reduce the drawn area.`);
    return false;
  }

  const lines: string[] = [];

  // Header
  lines.push('; ZX Spectrum UDG Sprite Data');
  lines.push('; Generated by ZX Spectrum UDG Editor');
  lines.push(';');
  lines.push(`; Sprite dimensions: ${exportWidth}x${exportHeight} characters (${exportWidth * 8}x${exportHeight * 8} pixels)`);
  lines.push(`; Total characters: ${totalChars}`);
  lines.push(`; UDG data size: ${totalChars * 8} bytes`);
  lines.push(`; Attribute data size: ${totalChars} bytes`);
  lines.push('');

  // Constants
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Constants');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push(`SPRITE_WIDTH    equ ${exportWidth}          ; Width in characters`);
  lines.push(`SPRITE_HEIGHT   equ ${exportHeight}          ; Height in characters`);
  lines.push(`SPRITE_CHARS    equ ${totalChars}         ; Total characters`);
  lines.push(`UDG_BYTES       equ ${totalChars * 8}        ; Bytes of UDG pixel data`);
  lines.push(`FIRST_UDG_CHAR  equ 144         ; First UDG character code`);
  lines.push('');

  // UDG pixel data - compact format (8 bytes per line = 1 character)
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; UDG Pixel Data (8 bytes per character, MSB=leftmost pixel)');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('sprite_udg_data:');

  let charIndex = 0;
  for (let charY = minCharY; charY < minCharY + exportHeight; charY++) {
    for (let charX = minCharX; charX < minCharX + exportWidth; charX++) {
      const bytes: string[] = [];
      for (let row = 0; row < CHAR_SIZE; row++) {
        let byte = 0;
        for (let col = 0; col < CHAR_SIZE; col++) {
          const pixelX = charX * CHAR_SIZE + col;
          const pixelY = charY * CHAR_SIZE + row;
          if (pixels[pixelY][pixelX]) {
            byte |= 1 << (7 - col);
          }
        }
        bytes.push(`$${byte.toString(16).padStart(2, '0').toUpperCase()}`);
      }
      lines.push(`        defb ${bytes.join(',')}  ; char ${charIndex} (row ${charY - minCharY}, col ${charX - minCharX})`);
      charIndex++;
    }
  }

  lines.push('');

  // Attribute data
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Attribute Data (1 byte per character)');
  lines.push('; Format: 0BPPPIII where B=bright, P=paper(0-7), I=ink(0-7)');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('sprite_attr_data:');

  for (let charY = minCharY; charY < minCharY + exportHeight; charY++) {
    const rowAttrs: string[] = [];
    for (let charX = minCharX; charX < minCharX + exportWidth; charX++) {
      const attr = attributes[charY][charX];
      const byte = (attr.bright ? 0x40 : 0) | (attr.paper << 3) | attr.ink;
      rowAttrs.push(`$${byte.toString(16).padStart(2, '0').toUpperCase()}`);
    }
    lines.push(`        defb ${rowAttrs.join(',')}  ; row ${charY - minCharY}`);
  }

  lines.push('');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Usage Example');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push(';');
  lines.push('; To use this sprite in your game:');
  lines.push(';');
  lines.push('; 1. Include this file in your project');
  lines.push(';');
  lines.push('; 2. Set up UDGs at startup:');
  lines.push(';        ld hl,sprite_udg_data');
  lines.push(';        ld (23675),hl           ; Set UDG system variable');
  lines.push(';');
  lines.push('; 3. Print sprite at screen position (row,col):');
  lines.push(';        call print_sprite');
  lines.push(';');
  lines.push('; Or copy UDG data to a custom location:');
  lines.push(';        ld hl,sprite_udg_data');
  lines.push(';        ld de,your_udg_buffer');
  lines.push(';        ld bc,UDG_BYTES');
  lines.push(';        ldir');
  lines.push('');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Helper Routines (optional - remove if not needed)');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('');
  lines.push('; Print sprite at position (B=row, C=col)');
  lines.push('; Modifies: AF, BC, DE, HL');
  lines.push('print_sprite:');
  lines.push('        ld d,SPRITE_HEIGHT');
  lines.push('        ld e,FIRST_UDG_CHAR');
  lines.push('_ps_row_loop:');
  lines.push('        push bc');
  lines.push('        push de');
  lines.push('        ; Position cursor (AT row,col)');
  lines.push('        ld a,22');
  lines.push('        rst 16');
  lines.push('        ld a,b');
  lines.push('        rst 16');
  lines.push('        ld a,c');
  lines.push('        rst 16');
  lines.push('        ; Print row of UDGs');
  lines.push('        ld b,SPRITE_WIDTH');
  lines.push('_ps_col_loop:');
  lines.push('        ld a,e');
  lines.push('        rst 16');
  lines.push('        inc e');
  lines.push('        djnz _ps_col_loop');
  lines.push('        pop de');
  lines.push('        pop bc');
  lines.push('        ; Move to next row');
  lines.push('        ld a,e');
  lines.push('        add a,SPRITE_WIDTH');
  lines.push('        ld e,a');
  lines.push('        inc b');
  lines.push('        dec d');
  lines.push('        jr nz,_ps_row_loop');
  lines.push('        ret');
  lines.push('');
  lines.push('; Set attributes for sprite at position (B=row, C=col)');
  lines.push('; Modifies: AF, BC, DE, HL');
  lines.push('set_sprite_attrs:');
  lines.push('        ld hl,sprite_attr_data');
  lines.push('        ld d,SPRITE_HEIGHT');
  lines.push('_sa_row_loop:');
  lines.push('        push bc');
  lines.push('        push de');
  lines.push('        ; Calculate attribute address: 22528 + row*32 + col');
  lines.push('        ld a,b');
  lines.push('        rrca');
  lines.push('        rrca');
  lines.push('        rrca');
  lines.push('        ld e,a');
  lines.push('        and $E0');
  lines.push('        ld d,a');
  lines.push('        ld a,e');
  lines.push('        and $03');
  lines.push('        or $58                  ; High byte of attr area');
  lines.push('        ld d,a');
  lines.push('        ld a,b');
  lines.push('        rlca');
  lines.push('        rlca');
  lines.push('        rlca');
  lines.push('        rlca');
  lines.push('        rlca');
  lines.push('        and $E0');
  lines.push('        or c');
  lines.push('        ld e,a');
  lines.push('        ; Copy attribute row');
  lines.push('        ld b,SPRITE_WIDTH');
  lines.push('_sa_col_loop:');
  lines.push('        ld a,(hl)');
  lines.push('        ld (de),a');
  lines.push('        inc hl');
  lines.push('        inc e');
  lines.push('        djnz _sa_col_loop');
  lines.push('        pop de');
  lines.push('        pop bc');
  lines.push('        inc b');
  lines.push('        dec d');
  lines.push('        jr nz,_sa_row_loop');
  lines.push('        ret');
  lines.push('');

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileName}.asm`;
  a.click();
  URL.revokeObjectURL(url);

  return true;
}
