import { MusicInstrument, MusicPattern, NoteName, NOTE_OFF } from '@/types';
import { NOTE_NAMES, MIN_OCTAVE, MAX_OCTAVE, noteToPeriod } from '@/constants';

interface MusicExportParams {
  patterns: MusicPattern[];
  instruments: MusicInstrument[];
  orderList: number[];
  ticksPerRow: number;
  fileName: string;
}

const NOTE_NONE = 0xff;
const NOTE_OFF_BYTE = 0xfe;
const INST_NONE = 0xff;
const VOL_USE_ENVELOPE = 0xff;
const ENVELOPE_LEN = 16; // fixed-length envelopes keep the exported player simple

function hex(n: number): string {
  return `$${(n & 0xff).toString(16).padStart(2, '0').toUpperCase()}`;
}

function noteIndex(note: NoteName, octave: number): number {
  return octave * NOTE_NAMES.length + NOTE_NAMES.indexOf(note);
}

function fitEnvelope(env: number[], loopStart: number): { steps: number[]; loop: number } {
  const steps = Array.from({ length: ENVELOPE_LEN }, (_, i) => env[i] ?? env[env.length - 1] ?? 0);
  const loop = Math.max(0, Math.min(ENVELOPE_LEN - 1, loopStart));
  return { steps, loop };
}

// Generates a self-contained, pasmo-assemblable .asm: an AY tone-period table,
// per-instrument volume envelopes, pattern/order data, and a 50Hz player
// routine driven by the standard halt-based main loop (see mr_soft_demo.asm).
// Register conventions mirror utils/ayEmulator.ts: the mixer byte built by the
// player uses 1=ON internally and is inverted to the chip's active-low wire
// format only at the point AY register 7 is written.
//
// v1 scope: note/instrument/volume columns are played; the effect/param
// columns and per-instrument noise are exported for reference but not
// interpreted by this reference player.
export function exportMusicASM({ patterns, instruments, orderList, ticksPerRow, fileName }: MusicExportParams): boolean {
  const lines: string[] = [];

  lines.push('; ZX Spectrum 128K AY-3-8912 Tracker Music Data');
  lines.push('; Generated by ZX Spectrum Music Editor');
  lines.push(';');
  lines.push(`; Assemble: pasmo --tapbas ${fileName}.asm ${fileName}.tap`);
  lines.push(`; Run:      fuse ${fileName}.tap`);
  lines.push('; (Entry point is called via BASIC: RANDOMIZE USR 32768)');
  lines.push(';');
  lines.push(`; Patterns: ${patterns.length}, Instruments: ${instruments.length}, Order length: ${orderList.length}`);
  lines.push(`; Ticks per row: ${ticksPerRow} (50Hz frames)`);
  lines.push(';');
  lines.push('; NOTE: effect/param columns and per-instrument noise are exported for');
  lines.push('; reference but not interpreted by this reference player (v1 plays');
  lines.push('; note/instrument/volume only). Extend music_tick to add them.');
  lines.push('');
  lines.push('        org     $8000');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Constants');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('AY_SEL          equ $FFFD       ; AY register select port (128K)');
  lines.push('AY_DATA         equ $BFFD       ; AY register data port (128K)');
  lines.push(`TICKS_PER_ROW   equ ${ticksPerRow}`);
  lines.push(`ORDER_LENGTH    equ ${orderList.length}`);
  lines.push('NOTE_NONE       equ $FF         ; row holds previous note');
  lines.push('NOTE_OFF        equ $FE         ; silence channel');
  lines.push('INST_NONE       equ $FF');
  lines.push('VOL_ENVELOPE    equ $FF         ; use instrument envelope, not fixed volume');
  lines.push('ENV_LEN         equ 16          ; fixed envelope length');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Entry point');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('start:');
  lines.push('        call    music_init');
  lines.push('halt_loop:');
  lines.push('        halt                    ; wait for 50Hz vsync interrupt');
  lines.push('        call    music_tick');
  lines.push('        jr      halt_loop');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; AY Tone Period Table (12-bit periods, one word per note)');
  lines.push('; Index = octave*12 + semitone (C=0 .. B=11), octaves 0-7');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('period_table:');
  for (let octave = MIN_OCTAVE; octave <= MAX_OCTAVE; octave++) {
    const periods = NOTE_NAMES.map((n) => noteToPeriod(n, octave));
    lines.push(`        defw ${periods.join(',')}  ; octave ${octave}: ${NOTE_NAMES.join(',')}`);
  }
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Instrument Volume Envelopes (16 steps of 0-15, one step per tick)');
  lines.push('; -----------------------------------------------------------------------------');
  const fitted = instruments.map((inst) => fitEnvelope(inst.volumeEnvelope, inst.loopStart));
  instruments.forEach((inst, i) => {
    lines.push(`instrument_${i}_env:  ; "${inst.name}"`);
    lines.push(`        defb ${fitted[i].steps.join(',')}`);
  });
  lines.push('');
  lines.push('instrument_env_table:');
  instruments.forEach((_, i) => lines.push(`        defw instrument_${i}_env`));
  lines.push('instrument_loop_table:');
  instruments.forEach((_, i) => lines.push(`        defb ${fitted[i].loop}`));
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Pattern Data');
  lines.push('; Each row: defb note, instrument, volume, effect, param (5 bytes)');
  lines.push('; note: 0-95 = note index into period_table, $FF = none, $FE = note off');
  lines.push('; volume: 0-15 = fixed volume, $FF = use instrument envelope');
  lines.push('; -----------------------------------------------------------------------------');
  patterns.forEach((pattern, pi) => {
    lines.push(`PATTERN_${pi}_ROWS equ ${pattern.rows}`);
    for (let ch = 0; ch < pattern.cells.length; ch++) {
      lines.push(`pattern_${pi}_ch${ch}:  ; "${pattern.name}" channel ${ch}`);
      for (let row = 0; row < pattern.rows; row++) {
        const cell = pattern.cells[ch][row];
        const note =
          cell.note === NOTE_OFF ? NOTE_OFF_BYTE : cell.note ? noteIndex(cell.note, cell.octave) : NOTE_NONE;
        const inst = cell.instrument ?? INST_NONE;
        const vol = cell.volume ?? VOL_USE_ENVELOPE;
        const effectCode = { none: 0, arpeggio: 1, slide_up: 2, slide_down: 3 }[cell.effect];
        lines.push(`        defb ${hex(note)},${hex(inst)},${hex(vol)},${hex(effectCode)},${hex(cell.effectParam)}  ; row ${row}`);
      }
    }
    lines.push('');
  });

  lines.push('channel_table_ptrs:');
  lines.push('        defw pattern_ch0_table,pattern_ch1_table,pattern_ch2_table');
  lines.push('pattern_ch0_table:');
  patterns.forEach((_, pi) => lines.push(`        defw pattern_${pi}_ch0`));
  lines.push('pattern_ch1_table:');
  patterns.forEach((_, pi) => lines.push(`        defw pattern_${pi}_ch1`));
  lines.push('pattern_ch2_table:');
  patterns.forEach((_, pi) => lines.push(`        defw pattern_${pi}_ch2`));
  lines.push('pattern_rows_table:');
  patterns.forEach((_, pi) => lines.push(`        defb PATTERN_${pi}_ROWS`));
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Order Table (sequence of pattern indices)');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('order_table:');
  lines.push(`        defb ${orderList.join(',')}`);
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Player State');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('cur_order_pos:  defb 0');
  lines.push('cur_row:        defb 0');
  lines.push('cur_tick:       defb 0');
  lines.push('cur_pattern:    defb 0');
  lines.push('; Per-channel state (indexed 0-2): active flag, instrument, fixed volume');
  lines.push('; override (VOL_ENVELOPE = none) and current envelope step.');
  lines.push('ch_active:      defb 0,0,0');
  lines.push('ch_inst:        defb INST_NONE,INST_NONE,INST_NONE');
  lines.push('ch_fixed_vol:   defb VOL_ENVELOPE,VOL_ENVELOPE,VOL_ENVELOPE');
  lines.push('ch_env_step:    defb 0,0,0');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; music_init - call once before the main loop starts');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('music_init:');
  lines.push('        xor     a');
  lines.push('        ld      (cur_order_pos),a');
  lines.push('        ld      (cur_row),a');
  lines.push('        ld      (cur_tick),a');
  lines.push('        ld      (ch_active),a');
  lines.push('        ld      (ch_active+1),a');
  lines.push('        ld      (ch_active+2),a');
  lines.push('        ret');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; ay_write - A = register, E = value. Modifies: AF, BC');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('ay_write:');
  lines.push('        push    bc');
  lines.push('        ld      bc,AY_SEL');
  lines.push('        out     (c),a');
  lines.push('        ld      a,e');
  lines.push('        ld      bc,AY_DATA');
  lines.push('        out     (c),a');
  lines.push('        pop     bc');
  lines.push('        ret');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; music_tick - call once per 50Hz frame (e.g. after halt in the main loop)');
  lines.push('; Modifies: all registers');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('music_tick:');
  lines.push('        ld      a,(cur_tick)');
  lines.push('        or      a');
  lines.push('        jr      nz,_mt_skip_row');
  lines.push('        ld      a,TICKS_PER_ROW');
  lines.push('        ld      (cur_tick),a');
  lines.push('        call    _mt_play_row');
  lines.push('        jr      _mt_envelopes');
  lines.push('_mt_skip_row:');
  lines.push('        dec     a');
  lines.push('        ld      (cur_tick),a');
  lines.push('_mt_envelopes:');
  lines.push('        ld      b,0');
  lines.push('        call    _mt_apply_channel');
  lines.push('        ld      b,1');
  lines.push('        call    _mt_apply_channel');
  lines.push('        ld      b,2');
  lines.push('        call    _mt_apply_channel');
  lines.push('        ret');
  lines.push('');

  lines.push('; Reads note/instrument/volume for all 3 channels at cur_row, writes tone');
  lines.push('; periods + mixer, then advances row/order position.');
  lines.push('_mt_play_row:');
  lines.push('        ld      a,(cur_order_pos)');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        ld      de,order_table');
  lines.push('        add     hl,de');
  lines.push('        ld      a,(hl)');
  lines.push('        ld      (cur_pattern),a');
  lines.push('        ld      b,0');
  lines.push('        call    _mt_play_channel');
  lines.push('        ld      b,1');
  lines.push('        call    _mt_play_channel');
  lines.push('        ld      b,2');
  lines.push('        call    _mt_play_channel');
  lines.push('        ; build mixer byte: bits 0-2 = tone enable (1=ON internally),');
  lines.push("        ; then invert to the chip's active-low wire format.");
  lines.push('        ld      a,(ch_active)');
  lines.push('        ld      c,a');
  lines.push('        ld      a,(ch_active+1)');
  lines.push('        rlca');
  lines.push('        or      c');
  lines.push('        ld      c,a');
  lines.push('        ld      a,(ch_active+2)');
  lines.push('        rlca');
  lines.push('        rlca');
  lines.push('        or      c');
  lines.push('        cpl');
  lines.push('        and     $3F');
  lines.push('        or      $C0');
  lines.push('        ld      e,a');
  lines.push('        ld      a,7');
  lines.push('        call    ay_write');
  lines.push('        ; advance row / order position');
  lines.push('        ld      a,(cur_pattern)');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        ld      de,pattern_rows_table');
  lines.push('        add     hl,de');
  lines.push('        ld      a,(hl)              ; A = row count for this pattern');
  lines.push('        ld      hl,cur_row');
  lines.push('        inc     (hl)');
  lines.push('        cp      (hl)');
  lines.push('        jr      nz,_mt_row_done');
  lines.push('        ld      (hl),0');
  lines.push('        ld      a,(cur_order_pos)');
  lines.push('        inc     a');
  lines.push('        cp      ORDER_LENGTH');
  lines.push('        jr      nz,_mt_no_wrap');
  lines.push('        xor     a');
  lines.push('_mt_no_wrap:');
  lines.push('        ld      (cur_order_pos),a');
  lines.push('_mt_row_done:');
  lines.push('        ret');
  lines.push('');

  lines.push('; Reads pattern_<cur_pattern>_ch<B>[cur_row] and updates channel B state.');
  lines.push('; B = channel (0-2) on entry. Modifies AF, BC, DE, HL, IX.');
  lines.push('_mt_play_channel:');
  lines.push('        push    bc                  ; preserve channel number (B) across address calc');
  lines.push('        ld      a,b');
  lines.push('        add     a,a                 ; x2 for word table index');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        ld      de,channel_table_ptrs');
  lines.push('        add     hl,de');
  lines.push('        ld      e,(hl)');
  lines.push('        inc     hl');
  lines.push('        ld      d,(hl)              ; DE = pattern_chB_table address');
  lines.push('        ld      a,(cur_pattern)');
  lines.push('        add     a,a');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        add     hl,de');
  lines.push('        ld      e,(hl)');
  lines.push('        inc     hl');
  lines.push('        ld      d,(hl)              ; DE = base of row data for this pattern/channel');
  lines.push('        ld      a,(cur_row)');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        ld      c,l');
  lines.push('        ld      b,h                 ; BC = row');
  lines.push('        add     hl,hl               ; row*2');
  lines.push('        add     hl,hl               ; row*4');
  lines.push('        add     hl,bc               ; row*5');
  lines.push('        add     hl,de               ; HL = row data address');
  lines.push('        push    hl');
  lines.push('        pop     ix                  ; IX = row data address (note,inst,vol,fx,param)');
  lines.push('        pop     bc                  ; B = channel number again');
  lines.push('        ld      a,(ix+0)');
  lines.push('        cp      NOTE_NONE');
  lines.push('        ret     z                   ; no event this row - leave channel state untouched');
  lines.push('        cp      NOTE_OFF');
  lines.push('        jr      z,_mt_pc_off');
  lines.push('        ; --- new note: mark active, store instrument/volume, reset envelope ---');
  lines.push('        ld      c,b                 ; BC = channel offset');
  lines.push('        ld      hl,ch_active');
  lines.push('        add     hl,bc');
  lines.push('        ld      (hl),1');
  lines.push('        ld      hl,ch_inst');
  lines.push('        add     hl,bc');
  lines.push('        ld      a,(ix+1)');
  lines.push('        ld      (hl),a');
  lines.push('        ld      hl,ch_fixed_vol');
  lines.push('        add     hl,bc');
  lines.push('        ld      a,(ix+2)');
  lines.push('        ld      (hl),a');
  lines.push('        ld      hl,ch_env_step');
  lines.push('        add     hl,bc');
  lines.push('        ld      (hl),0');
  lines.push('        ; --- set tone period ---');
  lines.push('        ld      a,(ix+0)');
  lines.push('        add     a,a');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        ld      de,period_table');
  lines.push('        add     hl,de');
  lines.push('        ld      e,(hl)');
  lines.push('        inc     hl');
  lines.push('        ld      d,(hl)              ; DE = period (E=fine, D=coarse)');
  lines.push('        ld      a,b');
  lines.push('        add     a,a                 ; reg = channel*2 (tone fine register)');
  lines.push('        call    ay_write            ; E already = fine period byte');
  lines.push('        inc     a');
  lines.push('        ld      e,d');
  lines.push('        call    ay_write            ; writes coarse period byte');
  lines.push('        ret');
  lines.push('_mt_pc_off:');
  lines.push('        ld      c,b');
  lines.push('        ld      hl,ch_active');
  lines.push('        add     hl,bc');
  lines.push('        ld      (hl),0');
  lines.push('        ret');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; _mt_apply_channel - B = channel (0-2). Writes the AY volume register for');
  lines.push('; this channel, advancing its envelope step if it has no fixed-volume');
  lines.push('; override. Modifies: AF, BC, DE, HL.');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push('_mt_apply_channel:');
  lines.push('        ld      c,b                 ; BC = channel offset (B=C=channel)');
  lines.push('        ld      hl,ch_active');
  lines.push('        add     hl,bc');
  lines.push('        ld      a,(hl)');
  lines.push('        or      a');
  lines.push('        jr      z,_mt_ac_silent');
  lines.push('        ld      hl,ch_inst');
  lines.push('        add     hl,bc');
  lines.push('        ld      a,(hl)');
  lines.push('        cp      INST_NONE');
  lines.push('        jr      z,_mt_ac_silent');
  lines.push('        ld      d,a                 ; D = instrument index');
  lines.push('        ld      hl,ch_fixed_vol');
  lines.push('        add     hl,bc');
  lines.push('        ld      a,(hl)');
  lines.push('        cp      VOL_ENVELOPE');
  lines.push('        jr      z,_mt_ac_envelope');
  lines.push('        ld      e,a');
  lines.push('        ld      a,b');
  lines.push('        add     a,8');
  lines.push('        call    ay_write');
  lines.push('        ret');
  lines.push('_mt_ac_envelope:');
  lines.push('        ld      hl,ch_env_step');
  lines.push('        add     hl,bc');
  lines.push('        ld      a,(hl)              ; A = current step');
  lines.push('        ld      e,a                 ; E = step');
  lines.push('        ld      a,d                 ; D = instrument index');
  lines.push('        add     a,a');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        push    de');
  lines.push('        ld      de,instrument_env_table');
  lines.push('        add     hl,de');
  lines.push('        pop     de');
  lines.push('        ld      a,(hl)');
  lines.push('        inc     hl');
  lines.push('        ld      h,(hl)');
  lines.push('        ld      l,a                 ; HL = envelope base address');
  lines.push('        push    de                  ; save (D=instrument, E=step)');
  lines.push('        ld      d,0');
  lines.push('        add     hl,de               ; HL += step');
  lines.push('        ld      a,(hl)              ; A = volume level for this step');
  lines.push('        pop     de                  ; D=instrument, E=step restored');
  lines.push('        ld      e,a                 ; value to write = level');
  lines.push('        ld      a,b');
  lines.push('        add     a,8');
  lines.push('        call    ay_write');
  lines.push('        ; advance envelope step, wrapping to the loop point at ENV_LEN');
  lines.push('        ld      hl,ch_env_step');
  lines.push('        add     hl,bc');
  lines.push('        push    hl                  ; save pointer to ch_env_step[channel]');
  lines.push('        ld      a,(hl)');
  lines.push('        inc     a');
  lines.push('        cp      ENV_LEN');
  lines.push('        jr      nz,_mt_ac_step_ready');
  lines.push('        ld      a,d                 ; instrument index');
  lines.push('        ld      l,a');
  lines.push('        ld      h,0');
  lines.push('        ld      de,instrument_loop_table');
  lines.push('        add     hl,de');
  lines.push('        ld      a,(hl)');
  lines.push('_mt_ac_step_ready:');
  lines.push('        pop     hl                  ; HL = ch_env_step[channel] pointer');
  lines.push('        ld      (hl),a');
  lines.push('        ret');
  lines.push('_mt_ac_silent:');
  lines.push('        ld      a,b');
  lines.push('        add     a,8');
  lines.push('        ld      e,0');
  lines.push('        call    ay_write');
  lines.push('        ret');
  lines.push('');

  lines.push('; -----------------------------------------------------------------------------');
  lines.push('; Usage Example');
  lines.push('; -----------------------------------------------------------------------------');
  lines.push(`;   include "${fileName}.asm"`);
  lines.push(';   ; call music_init once, then call music_tick after every halt');
  lines.push(';   ; in your main loop (50 times/sec) to advance playback.');
  lines.push('');
  lines.push('        end     start');
  lines.push('');

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileName}.asm`;
  a.click();
  URL.revokeObjectURL(url);

  return true;
}
